### ISSUE TITLE
Address Component

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#130]
Create a component of address that:

I must receive the chain's ```IService``` so it can get the **IAddressService** and validate the address.

It must validate the address using the ```IAddressService.validateAddress```

- [ ] Button Paste
- [ ] Validate address
- [ ] Upload image and read the QR Code from the image
- [ ] Address book

**Comment by johnnyluo** [comment]
This will be implemented as part of send flow
