### ISSUE TITLE
Memo Component

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#131]
Create a component of the memo where it is collapsable

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/47d962ca-730c-4de2-a3cd-0e195fed82c6">

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/c1156ed9-646f-449b-b7ab-f6aca2fe56b2">

**Comment by johnnyluo** [comment]
This will be implemented as part of the Send Flow
