### ISSUE TITLE
Create a component to select the coins

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#132]
- [ ] Create a new View
- [ ] Reuse the coin component created
- [ ] Pass the selected coin to send view and reload all info to the selected coin
- [ ] Must be searchable

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/50471646-a545-4381-8511-7cf2e341207a">
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/e72e1566-d8c2-4ab3-9b2e-705f8b925c86">

**Comment by johnnyluo** [comment]
This will be addressed as part of the sending flow
