### ISSUE TITLE
BTN send/swap

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#145]
The "Send/Swap" button is currently placed on the wrong page and needs to be relocated to a more appropriate location within the app. 

Here’s the flow:

1. **Home Screen**: Lists all available blockchain networks.
2. **Chain Selection**: When a user clicks on a specific chain, they are directed to an internal page.
3. **Internal Page**: This page exclusively lists the coins and tokens associated with the selected chain. Here, the "Send/Swap" button should be placed.
4. **Coin/Token Selection**: If a user clicks on a specific coin or token, they are taken to a dedicated page showing only the selected item. On this page, the user can click on the item or the "Send" button to proceed to the send page.

**Comment by johnnyluo** [comment]
The button has been put into place , but the logic of send is not correct yet , so I will close this one , and then use #172  to address the send flow optimisation issue
