### ISSUE TITLE
[ADD] "chain" and "chainId" properties as part of each AdressBook entity

### ISSUE THREAD

**Issue by antoni0dev** [vultisig/vultisig-windows#297]
[ADD] "chain" and "chainId" properties as part of each AdressBook entity

**Comment by johnnyluo** [comment]
Maybe this one can be break down to multiple

**Comment by johnnyluo** [comment]
Currently this is from windows app 
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/f591527d-17c1-43ce-9340-09bf50582059">
This is from macOS app
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/21163330-5bee-4281-9973-a7c9d1051d25">

1. Add icon
2. Display network at the end
3. Name has been displayed twice on Windows

**Comment by johnnyluo** [comment]
this had been fixed
