### ISSUE TITLE
[ADD] Swap Flow

### ISSUE THREAD

**Issue by CopsLikeDonuts** [vultisig/vultisig-windows#330]
Introduce swap feature for windows app that works commonly to webapp. 
Consists of several steps:
1. Navigation to swap page and implement new route - Done
2. Swap page UI (main swap page layout, token select modal, confirmation modal etc) - Done
3. Internal component logic (input amount validation, add token to favourites, connect API, fetch all supported tokens etc) - In progress
4. Fetch swap quotes, fees and display on UI - Not started
5. Confirmation modal UI + data display - Not started
6. Approve modal for ERC20 assets UI + function call - Not started
7. Swap functionality (transaction broadcast, receive hash, adjust explorer link) - Not started

**Comment by johnnyluo** [comment]
closing
