### ISSUE TITLE
[INVESTIGATE & ADD] First run of app automatic as admin

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#340]
As the app needs to run as a admin on first startup please investigate how it automatically can get run as admin so user does not have to do it maunally. Please add when known.

GPT input for reference:

> To automatically start a Windows application as an administrator on first startup, you'll need to use a combination of manifest files and code. Here's a step-by-step guide to help you achieve this:
> 
> **Step 1: Create a manifest file**
> 
> Create a new file named `app.manifest` in the root directory of your project. This file will contain the necessary configuration to request administrator privileges.
> 
> Add the following code to `app.manifest`:
> ```xml
> <?xml version="1.0" encoding="utf-8"?>
> <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
>   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
>     <security>
>       <requestedPrivileges>
>         <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
>       </requestedPrivileges>
>     </security>
>   </trustInfo>
> </assembly>
> ```
> **Step 2: Embed the manifest file**
> 
> In your project settings, ensure that the `app.manifest` file is embedded as a resource. To do this:
> 
> * In Visual Studio, right-click on the project and select **Properties**.
> * In the **Application** tab, click on the **Resources** button.
> * In the **Resources** window, click on the **Add Resource** button and select **Manifest**.
> * Select the `app.manifest` file and click **Open**.
> 
> **Step 3: Write code to handle the first startup**
> 
> In your application's code, you'll need to detect whether it's the first startup and, if so, request administrator privileges. You can use the following C# code as an example:
> ```csharp
> using System;
> using System.Diagnostics;
> using System.IO;
> using System.Security.Principal;
> 
> class Program
> {
>     static void Main(string[] args)
>     {
>         // Check if it's the first startup
>         string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "YourApp", "firststart.txt");
>         if (!File.Exists(filePath))
>         {
>             // Request administrator privileges
>             ProcessStartInfo startInfo = new ProcessStartInfo();
>             startInfo.UseShellExecute = true;
>             startInfo.WorkingDirectory = Environment.CurrentDirectory;
>             startInfo.FileName = System.Reflection.Assembly.GetExecutingAssembly().Location;
>             startInfo.Verb = "runas";
>             try
>             {
>                 Process.Start(startInfo);
>                 Environment.Exit(0);
>             }
>             catch (Exception ex)
>             {
>                 Console.WriteLine("Failed to start as administrator: " + ex.Message);
>             }
>         }
>         else
>         {
>             // Continue with normal application execution
>         }
>     }
> }
> ```
> This code checks for the existence of a file named `firststart.txt` in the application's data directory. If the file doesn't exist, it requests administrator privileges using the `runas` verb and restarts the application.
> 
> **Step 4: Create the `firststart.txt` file**
> 
> After the application has started as an administrator, create the `firststart.txt` file to prevent the application from requesting administrator privileges again on subsequent startups.
> 
> You can add the following code to create the file:
> ```csharp
> // Create the firststart.txt file
> string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "YourApp", "firststart.txt");
> File.Create(filePath).Dispose();
> ```
> That's it! With these steps, your Windows application should automatically start as an administrator on first startup and continue to run normally on subsequent startups.
> 
> **Created/Modified files during execution:**
> 
> * `app.manifest`
> * `firststart.txt`

**Comment by johnnyluo** [comment]
1. I managed to emedded a manifest file into the executable , so the next release when user open the app, it will be in administator
2. We are also in progress to purchase a certification to sign the exe and installation package , once that is ready , then windows will recognise us as a reputable publisher , and won't prompt unknown publisher dialog

**Comment by realpaaao** [comment]
@johnnyluo Thank you very much !

**Comment by johnnyluo** [comment]
We acquire certificate from digicert , moving forward , the app and the installation package will both be signed with the certificate , windows will prompt it is from an known publisher
