### ISSUE TITLE
[UPDATE] Onboarding flow UI/UX

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#345]
Please update onboarding flow according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=9327-20194&t=qjcNLkqm8Pr7HEGZ-4) to be able to include Vultiserver in vault creation.

**Comment by p-lopez100** [comment]
Connected with #344
