### ISSUE TITLE
[ADD] edit settings for Vault selection screens

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#354]
Please add the edit settings for the vault selection according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=16892-44992&t=usWXi6MXGoNWdrnE-4):

- [ ]  Remove Vault QR and refresh in Vault selection screen:
![Image](https://github.com/user-attachments/assets/15c93945-afda-44e0-a2b9-14f3485f9fa9)

- [ ] Add edit button that when toggled:

- [ ] Able to rearrange vaults and folders
- [ ] adds button to create folders

**Comment by johnnyluo** [comment]
I think this one is duplicate with #355
