### ISSUE TITLE
[BUG] Unable to use checkboxes without admin rights

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#360]
**Describe the bug**
The app does not allow to use checkboxes/toggles without starting the app with administrator permissions.

**Expected behavior**
Able to use the app without admin permissions

 - Version 1

**Additional context**
Users can easily think that app is broken if not able to select and navigate without admin permissions

**Comment by johnnyluo** [comment]
I think that only apply for the first time when we start the app right after install it, after that , it should works fine
I will add manifest file to the build , so it will request admin permission automatically

**Comment by realpaaao** [comment]
@johnnyluo sadly not. I have it every time I start it without admin rights

**Comment by johnnyluo** [comment]
I can build the app to not request admin permission , it seems works fine as well

**Comment by p-lopez100** [comment]
Close for now. If issue persists we will open new ticket.
