### ISSUE TITLE
[BUG] gas prices / fees not being shown

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#369]
We have to use a minimum of 8 places for decimals whenever it a TOKEN/Coin, FIAT uses only 2

Lets always use coin.decimals

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/a421e707-e20e-4453-a531-d649ee88a071">

**Comment by johnnyluo** [comment]
by getting latest from main branch , this one has been fixed , but correct , need to respect `coin.decimals`

**Comment by johnnyluo** [comment]
this has been fixed
