### ISSUE TITLE
[BUG] Decimal Places

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#379]
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/b730bab4-3a3a-4907-bf02-dee890238794">

We need to define the decimal places of tokens and coins as coin.decimals. 

My balance is probably 0.0000001213.....

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/1e3cb8c3-2b16-4103-a3b6-c4a9cb89ccc8">
 Same here

**Comment by johnnyluo** [comment]
duplicated #369 , closing
