### ISSUE TITLE
[ADD] Sorting of EVM tokens

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#403]
Please sort Tokens of EVM chains according to relevance, please refer to iOS and android for grouping.

**Comment by enriquesouza** [comment]
We have a chain


Header is equal the chain, plus total balance of all tokens


The Items are the tokens

1 - tokens filter(f=> f.nativetoken)
2 - tokens filter (f> !f.nativetoken).sortby(f.balance, 'desc')
