### ISSUE TITLE
[BUG] Set Swap affiliate fee address to `va`

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-windows#442]
**Describe the bug**
Please set affiliate fee address to `va`

**Comment by CopsLikeDonuts** [comment]
Backend issue. It was discussed with MAYA team and should be changed on API side. Will ask Jano about it

**Comment by CopsLikeDonuts** [comment]
this is not a FE bug, FE receives quotes from API with constructed memo. So will ask Jano how we can manage this

**Comment by johnnyluo** [comment]
since we sent `Platform: 'vulti-windows'` header to server , so server could then set the affiliate address to `va` if it see the header

**Comment by CopsLikeDonuts** [comment]
yes, we thought about it too
