### ISSUE TITLE
[BUG] Add Maya swap support

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-windows#443]
**Describe the bug**
Currently , when I select CACAO -> RUNE , it happily report quote , but it doesn't allow it on verify screen

**Comment by CopsLikeDonuts** [comment]
Thats because swap CACAO via MAYA protocol is a deposit transaction @johnnyluo

**Comment by p-lopez100** [comment]
Duplicate of #439. Closing to avoid duplicates
