### ISSUE TITLE
[ADD] Windows - portable / stand-alone binary

### ISSUE THREAD

**Issue by RowboTony** [vultisig/vultisig-windows#451]
**Is your feature request related to a problem? Please describe.**
Provide an executable binary to run Vultisig standalone, in a single directory, without installing to Windows OS.

**Describe the solution you'd like**
Ability to run multiple instanes of Windows Vultisig at the same time. For testing purposes, specifically to ensure my .vult backup files are vaild. I'd also like to test a 4 of 6 configuration or such for fun. Consider also, I'm traveling, and need to sign a transaction on a computer I have access to but do not own? The genius of Vultisig is the signing in real-time. I plugin the flash drive, run Vultisig, sign my transaction, done.

**Describe alternatives you've considered**
Alternatives are; using built-in Windows Sandbox, which is temporary, but cannot run multiple instances, and is not available on Windows Home/Retail version. Or a Virtual Machine can be configured, which is a lot of extra work for this simple use case.

**Comment by comanche** [comment]
I second this.

**Comment by johnnyluo** [comment]
I like the thinking here , I think we can do this right now, put `vultisig.exe` and `vultisig.db` in the same folder , then you should be able to run it
the app itself doesn't access anything else 
but I didn't test it , will keep this issue here.

**Comment by RowboTony** [comment]
It appears this is available now as of release v1.0.5. The `vultisig.exe` released here creates a `vultisig.db` in the running directory, and remembers the Vaults you import to this version. 👍

https://github.com/vultisig/vultisig-windows/releases/tag/v1.0.5

Closing request.
