### ISSUE TITLE
[BUG/INVESTIGATE] Updating app overwrites state

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#471]
**Describe the bug**
When installing an update (happened from the 1.0.2 to 1.0.3) the app overwrites all vault share leaving it with a blank app. Possibly losing all access if no backup was done.

**To Reproduce**
1. Update from 1.0.2 to 1.0.3
2. open app

**Expected behavior**
ALWAYS make sure that vault state is kept

 - Version 1.0.3

**Additional context**
Trying to reproduce the issue after installing the 1.0.3 the first time it is not possible to reproduce and vaults are kept. Need to verify on 1.0.4

**Comment by johnnyluo** [comment]
closing
