### ISSUE TITLE
[UPDATE] Information label on Vultiserver password

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#477]
Please update the information label on password input screen when creating a fast or active vault according to figma:
It should reflect `This Password encrypts your Vault Share received via email `

![Image](https://github.com/user-attachments/assets/4c4cf7f3-8804-4b8e-84ca-cf60df37fbf9)

**Comment by johnnyluo** [comment]
Based on my test , it has been fixed , so closing
