### ISSUE TITLE
[BUG] After updates no chains displayed

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#499]
**Describe the bug**
When updating removes all chains and they need to be enabled again.

 - Version 1.04.

**Comment by johnnyluo** [comment]
Can you please provide more detail descriptions? maybe a screenshot?

**Comment by realpaaao** [comment]
@johnnyluo after updating to the latest version non of the added vaults have any chains selected anymore and they are needed to be added again manually:

![image](https://github.com/user-attachments/assets/c9748151-2b63-43bb-85ea-f9b6c5f1c253)
