### ISSUE TITLE
[BUG] leaving folder edit mode triggers folder edit mode again

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#503]
**Describe the bug**
Entering the folder edit mode and pressing `done` and afterwards going back to vault selection screen toggles edit mode a second time

**To Reproduce**
1. open edit folder mode and press `done`
2. Go back to vault selection screen

**Expected behavior**
No double toggle

**Screenshots**

 - Version 1.0.4

**Comment by johnnyluo** [comment]
this had been fixed , likely in #526
