### ISSUE TITLE
[BUG] Wrong server message on reshare

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#508]
**Describe the bug**
When resharing a fast vault and putting in a bad password, the app doe not return a correct "Password is wrong" message.

**Expected behavior**
Please check for correct password and prompt the user correctly if it is a wrong password

**Screenshots**
![Image](https://github.com/user-attachments/assets/d7a35856-a8bd-4c9d-9bf9-d45a94535be6)

 - Version 1.0.4

**Comment by johnnyluo** [comment]
fixed in #532
