### ISSUE TITLE
[ADD] UI for vultiserver backup verification

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#529]
Please add a view that the user can put in a code to verify the receipt of the backup of his vultiserver backup share.
Please only trigger this view on vault creation where a vultiserver is included (fast or active vault).
Check against code saved on server.

![Image](https://github.com/user-attachments/assets/690dadc0-3bc8-4440-8c1d-4072c8930998)

**Comment by johnnyluo** [comment]
duplicate of #549 closing
