### ISSUE TITLE
[BUG] Missing addresses when swapping

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#534]
**Describe the bug**
Some chains to not populate the receiving address automatically when chain is not toggled. 

**Expected behavior**
Please make sure that when chain is not toggled on, user can't select asset on swap screen

 - Version 1.0.4

**Comment by p-lopez100** [comment]
@realpaaao please add screenshot

**Comment by p-lopez100** [comment]
No issue anymore. Closing
