### ISSUE TITLE
Create Coin Cell

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#59]
We have to create the coin Cell component. 

<img width="631" alt="image" src="https://github.com/user-attachments/assets/19339f1b-5b27-40f7-aebc-18f0a0528419">

This component must have:

- [x] Logo
- [x] Coin Ticker
- [x] Coin amount in decimal
- [x] Coin amount in FIAT
- [x] Coin address

**Comment by enriquesouza** [comment]
You can get the code from here:

https://github.com/vultisig/vultisig-windows/blob/rpc/frontend/src/pages/vault/VaultListView.tsx#L44

**Comment by johnnyluo** [comment]
closing
