### ISSUE TITLE
[BUG] unable to create fast Vault

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#607]
**Describe the bug**
It is not possible to create a fast vault. A error occurs after validating the vault with the code.

**To Reproduce**
1. Create Fast vault
2. Verify with verification code
3. See error

**Expected behavior**
Able to create fast vault

**Screenshots**
![Image](https://github.com/user-attachments/assets/1be69602-7e6f-47fc-82d3-a4533ffcec45)

**Desktop (please complete the following information):**
 - Version 1.0.6

**Comment by johnnyluo** [comment]
Your database is locked , do you have multiple vultisig instances open at the same time?

**Comment by johnnyluo** [comment]
This should have been fixed
