### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-windows#63]
- [ ] #64
- [x] #65
- [x] #66
- [ ] #67
- [ ] #68
- [x] #69
- [ ] #70
- [x] #71
- [x] #72
- [x] #73
- [ ] #74

We need to create a component.

A list with a component that has 

Icon | Name | Arrow

**Comment by enriquesouza** [comment]
![image](https://github.com/user-attachments/assets/66d2cfbf-9a0b-4a58-afce-c1faf70a8d31)

**Comment by johnnyluo** [comment]
closing, as this is the parent task
